language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t lea/react-test -f ./client/Dockerfile.dev ./client

script:   
  - docker run -e CI=true lea/react-test npm test -- --coverage

after_success:
  - docker build -t lea/multi-client ./client
  - docker build -t lea/multi-nginx ./nginx
  - docker build -t lea/multi-worker ./worker
  - docker build -t lea/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password stdin
  - docker push lea/multi-client 
  - docker push lea/multi-nginx 
  - docker push lea/multi-worker
  - docker push lea/multi-server